### ISSUE TITLE
Images and seasons?

### ISSUE THREAD

**Issue by bukusgithub** [BrianHepler/MMM-WeatherBackground#1]
Hey, was wondering if there was a way to add more images and base it on the season? i love using this however seeing green grass for the "sunny" day in the dead of winter is depressing lol. i could just change the images but id rather check if this is possible first.

**Comment by eouia** [comment]
Well, maybe it could be possible, but not so simple if you are not experienced in programming.

Open `MMM-weatherBackground.js` and see from line 14 to line 61. That is `default` converter which would convert from some weather info of each weather module to text query for unsplash.
You can redefine it in your `config.js`.
At the moment put your code for season. 
If you need more help, contact me. 
mail : eouia0819@gmail.com
Telegram : @eouia

**Comment by eouia** [comment]
I’ll close this issue.
