### ISSUE TITLE
Weather module

### ISSUE THREAD

**Issue by AlienPT** [BrianHepler/MMM-WeatherBackground#10]
Hi,
it's possible to connect this to actual "weather" module?
"currentweather" module has been deprecated.
Thank you

**Comment by BrianHepler** [comment]
Good idea. I'll take a look at it.

**Comment by BrianHepler** [comment]
I don't know how I forgot this issue. WeatherBackground supports the default "weather" module. If you encounter any problems using the default weather module, please let me know.
