### ISSUE TITLE
No Background Image being displayed

### ISSUE THREAD

**Issue by shak4031** [BrianHepler/MMM-WeatherBackground#12]
I am getting any background image.  Below is my config.

 {
        module: "MMM-WeatherBackground",
        config: {
          targetDOM: "", //null or DomSelector for target.
                // if null, currentweather will be targeted.
                // examples: ".newsfeed", "#SOME_SPECIAL_DOM", ".top.left .module"
                hemisphere: "n", // "n" (north) or "s" (southern) to establish the correct season of the year.
                source : "MMM-NOAA3", // `currentweather`, `MMM-NOAA3`, `MMM-DarkSkyForecast`
                }
},

**Comment by eouia** [comment]
Set targetDOM. Perhaps you want “.fullscreen.below”.
