### ISSUE TITLE
source.unsplash.com deprecated

### ISSUE THREAD

**Issue by mikeyounge** [BrianHepler/MMM-WeatherBackground#18]
It looks like the website that this module pulls from has deprecated the api that it using. Is it possible to reconfigure this to use the current API? It looks like it needs a key, but it shouldn't be too bad for personal use with 50hits/day. I've tried to look into it myself, but I'm not strong enough in javascript to know how to modify this to handle the API JSON response. Thanks for any help with this.

EDIT: It may have been a temporary outage because it has started working again, but I have read that it will be deprecated at some point.

**Comment by BrianHepler** [comment]
Well, nuts. I have looked at upgrading the module to use their new API using their developer registration. It has a bunch of requirements that I'm not sure are appropriate to this module, such as the necessity to hyperlink to the source, display the author and so forth. It's hard to hyperlink a background image on a read-only device.

I'm glad that it's functioning again, but it sounds like I should start a conversation with unsplash and see if I can get a waiver. They may be cool with us using the images so long as I display the author and URL.

**Comment by nathanbutler** [comment]
@BrianHepler I just wanted to say thank you very much for this. Really appreciate this module and is something I have been searching for years.

**Comment by BrianHepler** [comment]
Can you double check on the error for me? I just fired it up to troubleshoot it some more and it seems to be working fine. I'd rather not change this up if I don't have to.

**Comment by mikeyounge** [comment]
It has been working fine since I updated the original post. I'm not sure how long until it breaks again when they truly shut that API down. But for now, it's working. On Jan 5, 2023, at 8:12 PM, Brian Hepler ***@***.***> wrote:﻿
Can you double check on the error for me? I just fired it up to troubleshoot it some more and it seems to be working fine. I'd rather not change this up if I don't have to.
