### ISSUE TITLE
pull request 2023

### ISSUE THREAD

**Issue by mirrormonark** [BrianHepler/MMM-WeatherBackground#23]
hi, please add ability to enable video and sound

**Comment by BrianHepler** [comment]
Hi. No, I'm not going to do this. For a few reasons:
1. The website the module uses to pull the images only hosts images.
2. At present, the latest version of Raspian only includes VLC which is unsuitable for playing embedded video.
3. I have no idea how to resolve the conflict between a local sound file and the audio track on a video file.
4. I have no idea where to pull appropriate videos related to the current weather being broadcast by other modules.
5. I have no idea how to remove the advertisements from common free video websites.

All that said, if you can figure out how to enable such a feature and create a pull request, I will happily review it for consideration. Let me know if you have questions on how this module works.

**Comment by mirrormonark** [comment]
I am not very familiar with programming.
my idea was to have the videos locally (with sound or without sound) and associate them with the weather.. exactly like it is done with photos or taking cues from weather modules (weather icons). a downloaded video or gif does not contain advertisements. but i trust on what you say, if then there is the problem with vlc then i don't know if something can be done.
my example was

"rain"="rain.mp4" (maybe a video of city rain or mountain rain)
"snow"="snow.mp4" (maybe a video of snow coming down from the sky/over the mirror or a burning fireplace)

i think you would probably have to recreate it even with the images so that it just takes it locally and not from websites. it would be nice for me to do that, but I'm afraid of destroying something.
thank you for asnwer me.
