### ISSUE TITLE
Image transparency?

### ISSUE THREAD

**Issue by GoodWillGustin** [BrianHepler/MMM-WeatherBackground#6]
Is there a way to change the background image transparency? I love this module idea but would like it to be a more subtle sort of background indication of weather conditions. The current view makes it very hard to make out my modules' text, even with the recommended changes to my css file.

**Comment by eouia** [comment]
If your targetDom is `fullscreen_below`; add this into your `css/custom.css`
```css
.fullscreen.below {
  opacity: 0.5;
}
```
