### ISSUE TITLE
Background is always on

### ISSUE THREAD

**Issue by reallykeene** [BrianHepler/MMM-WeatherBackground#7]
I have multiple pages on my magic mirror and want this to display on only one. What do I need to change to fix this?

**Comment by eouia** [comment]
Install MMM-Dummy and put it into your target pate. Then add this into your config. `targetDOM: ".MMM-Dummy",`

**Comment by BrianHepler** [comment]
I'm just following up. @reallykeene, are you good to go with this module? Are you still experiencing problems?
