### ISSUE TITLE
does not start.

### ISSUE THREAD

**Issue by lacalos** [BrianHepler/MMM-WeatherBackground#9]
hello I start by telling you that I really like your module, but I can't get it started. now I'll explain what I want to do. First I tell you that I use as modules "PageSelector" and time module "MMM-Openmapweather". I did as it said and I did all the things. but the best and that makes me see the normal screen, without background.how can I do? what should I do? what should i change? thank you for your kind reply. best regards mister hepler

**Comment by BrianHepler** [comment]
I don't think `MMM-Openmapweather` is supported as a source for this module. This module supports  `currentweather`, `MMM-NOAA3`, `MMM-DarkSkyForecast`. Have you tried any of those sources?

You can put in a request for me to add MMM-OpenMapWeather support. That could be a fun project.

**Comment by lacalos** [comment]
please sir. can implement this fantastic module with the "openmapweather" time module. thank you so much

**Comment by lacalos** [comment]
Hello. how are you?
I have installed the NOOA3 module. but i can't get it to work. as provider of noaa3 is openweather. I would like to pin your form on a page and I downloaded DUMMY. how can I do? thank you.

**Comment by BrianHepler** [comment]
Okay, let's start with the basics. Please copy & paste the two parts of your `config.js` that control NOAA3 and MMM-WeatherBackground. Be sure to delete your API keys when you post. I don't need that part. Let's make sure that things are configured properly.

Just to be sure you see the NOAA3 module when your mirror is running, correct?

**Comment by lacalos** [comment]
this post can be closed. I managed to solve it I don't know how ahahahahah. I would like to ask you if in my form I can modify the image file? I'll explain, my idea is to put a GIF or a video with the sound (when possible) of the weather. example: strong wind, wind sound. storm with lightning? sound of lightning and so on. obviously it cannot be done for all types of weather, I mean the sound. but it would be nice. thanks for the availability mister

**Comment by BrianHepler** [comment]
Ok, I'll close it. I started on the openmapweather and I'm like 75% sure that it doesn't broadcast events like the documentation says it does. So I'm glad that you got it working.

Regarding the image file: you can specify your own image collection. If you look at the code in `MMM-WeatherBackground.js` you can see the format for the collection. Those numbers represent image IDs are collection numbers at the Unsplash website. You can provide your own collection information via the `config.js` configuration.

As for sound... that's beyond the scope of this module. If you want to develop the capability, I'll link to it. If you create a pull request, I'll consider it. But I'm not going to add sound to a background image module.

**Comment by lacalos** [comment]
Hello, how are you?. can I create it in my personal form? that is to
configure for me and still make a pull request of course.
my intention is to create in addition to the image also the sound of the
weather.
example:

rain with thunder: https://www.youtube.com/watch?v=HsQlpaYTE0s
snowstorm wind: https://www.youtube.com/watch?v=vplX-qr4AIE
summer: https://www.youtube.com/watch?v=HTc_2XmKK-M
summer night: https://www.youtube.com/watch?v=2Xzfy7zyt0A
winter: https://www.youtube.com/watch?v=I0oLjBDB2NQ

are examples of sound that can link with an image, gif or video. what do
you think? thank you for your time.

BEST REGARDS sir

Il giorno ven 2 lug 2021 alle ore 05:13 Brian Hepler <
***@***.***> ha scritto:

**Comment by BrianHepler** [comment]
You are more than welcome to create your own branch. In fact, I encourage it.
